[package]
name = "spin_sleep"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
description = "Accurate sleeping. Only use native sleep as far as it can be trusted, then spin"
repository = "https://github.com/alexheretic/spin-sleep"
keywords = ["sleep"]
license = "Apache-2.0"
