[package]
name = "spin_sleep"
version = "0.3.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
description = "Accurate sleeping. Only use native sleep as far as it can be trusted, then spin."
repository = "https://github.com/alexheretic/spin-sleep"
keywords = ["sleep"]
license = "Apache-2.0"
readme="README.md"

[dev-dependencies]
approx = "0.1.1"

[features]
# Controls certain tests that are not deterministic
nondeterministic_tests = []
