[package]
name = "spin_sleep"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
description = "Accurate sleeping. Only use thread::sleep as far as it can be trusted, then spin"
repository = "https://github.com/alexheretic/single-value-channel"
keywords = ["sleep"]
license = "Apache-2.0"

[dependencies]
